### ISSUE TITLE
这是集成在Hyperf中的mqtt协程客户端吗?

### ISSUE THREAD

**Issue by wenber-yu** [nashgao/mqtt-client#1]
您好, 是否支持使用阿里云的物联网mqtt平台

**Comment by nashgao** [comment]
你好 这个是集成hyperf的mqtt协程客户端 不过不是官方的项目 这边使用了simps/mqtt的依赖 应该是可以支持阿里云的mqtt平台的 

我自己有在项目中使用这个包 后续我可以写一下readme和文档

**Comment by wenber-yu** [comment]
感谢您的回复, 我目前想在项目中集成使用, 引入包后, 我把库自带的监听加到了config中的listener配置文件中, mqtt配置了一个mqttx的公共服务, 但是控制台没看到关于mqtt的信息, 所以有点蒙, 不是很了解您这个库的使用方式.
另外, 发现现在readme中关于composer require 包名写错了.

**Comment by nashgao** [comment]
谢谢你的使用 我之前有改过项目名称 但是readme里面忘记修改了 

控制台你是指cli还是阿里云？ 项目中我并没有使用std logger 这个是一个可以增加的地方

如果可以的话 能提供一个最小的复现例子吗

大概的思路是提供一个mqtt的客户端连接池 自己有一个这方面的需求 其次是添加了一个concurrent patten 使得客户端在sub的同时依然可以pub消息

**Comment by wenber-yu** [comment]
控制台指cli, 我理解的是, 在启动时候应该会去连接mqtt服务端, 然后类似启动信息一样, 再cli输出一些连接成功之类的提示. 不知道我理解的对不对. 

我目前的项目场景类型贴码支付这种, 用户拿付款码贴到扫码机上去扫码, 然后扫码机会通过mqtt上报二维码内容, mqtt再转发到我的mqtt客户端, 客户端进过业务处理, 再把处理结果发送给mqtt, mqtt再转发到扫码机. 

因为第一次接触物联网这块, 所以有些不是很明白. 

感谢回复. 另外是否可以加下您的qq, 在不影响您工作或生活的情况下, 可以请教您一些问题.

我的qq: 271041031

**Comment by wenber-yu** [comment]
我现在开启库的5个监听后, 在控制器中创建了client实例.
```php
#[Controller(prefix: CommonConstant::ROUTE_PATH_PREFIX.'/mqtt')]
class MqttController extends AbstractController
{
    #[Inject]
    protected ClientFactory $clientFactory;

    #[GetMapping(path: 'test')]
    public function index()
    {
        $config = new ClientConfig('broker-cn.emqx.io', 1883, new \Simps\MQTT\Config\ClientConfig());
        $client = $this->clientFactory->create($config, 'test');
        $result = $client->subscribe(['testtopic/#'], ['qos' => 2]);

        return $this->response->success(['result' => $result]);
    }
}
```
然后报错如下:
```bash
[2022-09-08 09:40:16 *87532.0]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Simps\MQTT\Exception\RuntimeException: Simps\MQTT\Tools\PackTool::string(): Argument #1 ($str) must be of type string, int given, called in /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Packet/Pack.php on line 98 in /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Protocol/V3.php:71
Stack trace:
#0 /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Client.php(212): Simps\MQTT\Protocol\V3::pack(Array)
#1 /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Client.php(105): Simps\MQTT\Client->send(Array)
#2 /Users/wilbur.yu/MyCode/Pwk/api/vendor/nashgao/mqtt/src/ClientProxy.php(76): Simps\MQTT\Client->subscribe(Array, Array)
#3 [internal function]: Nashgao\MQTT\ClientProxy->Nashgao\MQTT\{closure}()
#4 /Users/wilbur.yu/MyCode/Pwk/api/vendor/nashgao/mqtt/src/ClientProxy.php(49): Closure->call(Object(Nashgao\MQTT\ClientProxy))
#5 /Users/wilbur.yu/MyCode/Pwk/api/vendor/nashgao/mqtt/src/ClientFactory.php(17): Nashgao\MQTT\ClientProxy->loop()
#6 {main}
  thrown in /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Protocol/V3.php on line 71
[2022-09-08 09:40:16 $87530.0]	WARNING	Server::check_worker_exit_status(): worker(pid=87532, id=0) abnormal exit, status=255, signal=0
```
mqtt配置文件都是按默认的, 看报错信息是类型错误, 我试着把qos值改为字符串类型的, 也不行.

**Comment by nashgao** [comment]
我不是很常用qq 我晚些可以加你

如果设置好了配置文件 是不需要主动订阅的(如果auto_subscribe为true) 会在AfterWorkerStart事件触发后直接订阅

**Comment by nashgao** [comment]
如果你希望直接实例化一个clien然后订阅 那建议你用simps的mqtt组建 我主要是为了适配mqtt的shared topic这个特性 所以在配置文件中有shared topic和queue topic这样的选项 如果你想手动订阅 可以用hyperf事件派发器发送一个SubscribeEvent

**Comment by wenber-yu** [comment]
如果使用主动订阅, 那我发布消息, 也就是不用再创建一个客户端, 而是触发一个PublishEvent事件对吗.
我的微信: 18310086909, 您方便可以加我微信.

**Comment by wenber-yu** [comment]
mqtt.config
```php
return [
    'default' => [
        'host' => env('MQTT_HOST', 'localhost'),
        'port' => (int)env('MQTT_PORT', 1883),
        // http port option deprecated
        'http_port' => (int)env('MQTT_HTTP_PORT', 8081),
        'time_out' => (int)env('MQTT_TIMEOUT', 10),
        'keepalive' => (int)env('MQTT_KEEPALIVE', 60),
        'protocol_name' => 'MQTT',
        'protocol_level' => (int)env('MQTT_PROTOCOL_LEVEL', 5),
        'username' => env('MQTT_USERNAME', 'admin'),
        'password' => env('MQTT_PASSWORD', 'public'),
        'properties' => [

        ],
        'swoole_config' => [
            'package_max_length' => 1024 * 1024,
            'connect_timeout' => 5.0,
            'keepalive' => 0, // default 0 sec which means disabled
            'ssl_enabled' => '',
            'ssl_cert_file' => '',
            'ssl_key_file' => '',
            'ssl_cafile' => '',
        ],
        'http' => [
            'host' => (int)env('MQTT_HTTP_HOST', 'localhost'),
            'port' => (int)env('MQTT_HTTP_PORT', 8081),
            'app_id' => env('MQTT_HTTP_APP_ID', 'admin'),
            'app_secret' => env('MQTT_HTTP_APP_SECRET', 'public')
        ],
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 10,
            'connect_timeout' => 10.0,
            'wait_timeout' => 20.0,
            'heartbeat' => -1,
            'max_idle_time' => 60,
        ],
        'prefix' => '',
        'subscribe' => [
            'topics' => [
                [
                    'topic' => 'testtopic/#',
                    'auto_subscribe' => true,
                    'enable_multisub' => false,
                    'multisub_num' => 2, // let multiple subscribe the same topic, usually works with queue topic and shared topic
                    'enable_share_topic' => false,
                    'share_topic' => [
                        'group_name' => [], // list of group names that
                    ],
                    'enable_queue_topic' => false, // queue topic has more priority, if queue topic is define then share topic would be useless
                    'qos' => 2,
                    'filter' => null,
                    'no_local' => true,
                    'retain_as_published' => true,
                    'retain_handling' => 2,
                ],
            ],
        ],
        'publish' => [
            'topics' => [
                [
                    'topic' => 'testtopic/#',
                    'shared_topic' => '',
                    'qos' => 2,
                    'filter' => false,
                    'no_local' => true,
                    'retain_as_published' => true,
                    'retain_handling' => 2,
                ],
            ],
        ],
    ],
];
```
项目启动时, 报错:
```bash
Fatal error: Uncaught Simps\MQTT\Exception\RuntimeException: chr(): Argument #1 ($codepoint) must be of type int, array given in /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Protocol/V3.php:71
Stack trace:
#0 /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Client.php(212): Simps\MQTT\Protocol\V3::pack(Array)
#1 /Users/wilbur.yu/MyCode/Pwk/api/vendor/simps/mqtt/src/Client.php(105): Simps\MQTT\Client->send(Array)
#2 /Users/wilbur.yu/MyCode/Pwk/api/vendor/nashgao/mqtt/src/ClientProxy.php(76): Simps\MQTT\Client->subscribe(Array, Array)
#3 [internal function]: Nashgao\MQTT\ClientProxy->Nashgao\MQTT\{closure}()
#4 /Users/wilbur.yu/MyCode/Pwk/api/vendor/nashgao/mqtt/src/ClientProxy.php(49): Closure->call(Object(Nashgao\MQTT\ClientProxy))
#5 /Users/wilbur.yu/MyCode/Pwk/api/vendor/nashgao/mqtt/src/ClientFactory.php(17): Nashgao\MQTT\ClientProxy->loop()
```
然后在Simps\MQTT\Protocol\V3::pack方法的case Types::SUBSCRIBE分支, 进入Pack::subscribe方法后, 打印出传递的值为:
```php
array(4) {
  ["type"]=>
  int(8)
  ["message_id"]=>
  int(1)
  ["properties"]=>
  array(0) {
  }
  ["topics"]=>
  array(1) {
    ["testtopic/#"]=>
    array(4) {
      ["qos"]=>
      int(2)
      ["no_local"]=>
      bool(true)
      ["retain_as_published"]=>
      bool(true)
      ["retain_handling"]=>
      int(2)
    }
  }
}
```
但是Pack::subscribe方法
```php
public static function subscribe(array $array): string
    {
        var_dump($array);
        $id = $array['message_id'];
        $body = PackTool::shortInt($id);
        foreach ($array['topics'] as $topic => $qos) {
            $body .= PackTool::string($topic);
            $body .= chr($qos);
        }
        $head = PackTool::packHeader(Types::SUBSCRIBE, strlen($body), 0, 1);

        return $head . $body;
    }
```
对于 $qos的处理是chr
